### Variables
@taskId = 1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RJZCI6IjMzOTQ1NTk3LTgwYmEtNGE0Zi1hMWNkLWE0NzY5YTNkNzUwNSIsInVzZXJJZCI6MSwibmFtZSI6InVzZXItMDEiLCJlbWFpbCI6InVzZXItMDFAZXhhbXBsZS5jb20iLCJpYXQiOjE3ODAyOTYxNDIsImV4cCI6MTc4MDMzOTM0MiwiYXVkIjoia2FuYmFuLWJlIiwiaXNzIjoia2FuYmFuLWJlIn0.Xheuz7c_BoWOMVG_OiSGd8OMl6bpm8mNaIP8PS1MG_Q

### 1. Create a new Task
POST {{baseUrl}}/tasks
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "title": "Belajar Backend",
  "description": "Mempelajari dasar-dasar API dengan NestJS"
}

### 2. Get All Tasks
GET {{baseUrl}}/tasks
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### 3. Get Task by ID
GET {{baseUrl}}/tasks/{{taskId}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### 4. Update Task by ID
PATCH {{baseUrl}}/tasks/{{taskId}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "title": "Belajar NestJS Lanjutan",
  "status": "ON_PROGRESS"
}

### 5. Delete Task by ID
DELETE {{baseUrl}}/tasks/{{taskId}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}
