### Variables
@taskId = 12
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RJZCI6IjIwYWUyOTZiLTgzNjMtNDY0MS1hZTAxLTAzMmE4NTZiNzNmNSIsInVzZXJJZCI6MTQsIm5hbWUiOiJ1c2VyLTQ3MzgiLCJlbWFpbCI6InVzZXItNDczOEBleGFtcGxlLmNvbSIsImlhdCI6MTc4MDI0MTYxMiwiZXhwIjoxNzgwMjg0ODEyLCJhdWQiOiJrYW5iYW4tYmUiLCJpc3MiOiJrYW5iYW4tYmUifQ.pgozkUGivAMIv3PhtHHUXPYuOwBy0ZqzWkGfQBME9qo

### 1. Create a new Task
POST {{baseUrl}}/tasks
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "title": "Belajar Backend",
  "description": "Mempelajari dasar-dasar API dengan NestJS"
}

### 2. Get All Tasks
GET {{baseUrl}}/tasks
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### 3. Get Task by ID
GET {{baseUrl}}/tasks/{{taskId}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### 4. Update Task by ID
PATCH {{baseUrl}}/tasks/{{taskId}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "title": "Belajar NestJS Lanjutan",
  "status": "ON_PROGRESS"
}

### 5. Delete Task by ID
DELETE {{baseUrl}}/tasks/{{taskId}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}
