### Variables
@rand = {{ $randomInt 1 10000}}
@password = Password123

### 1. Register New User
POST {{baseUrl}}/users/register
Content-Type: application/json
Accept: application/json

{
  "name": "user-{{rand}}",
  "email": "user-{{rand}}@example.com",
  "password": "{{password}}"
}

### 2. Login User
POST {{baseUrl}}/users/login 
Content-Type: application/json
Accept: application/json

{
  "email": "user-4738@example.com",
  "password": "{{password}}"
}